project_id = "ywhhuihplgguensdmuzh"

[functions.asaas-webhook]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false

[functions.create-invite]
verify_jwt = false

[functions.asaas-payments]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.import-foods]
verify_jwt = false

[functions.email-webhook]
verify_jwt = false

[functions.generate-diet-plan]
verify_jwt = false

[functions.process-knowledge-document]
verify_jwt = false
